[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (optional - set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
